@startuml "Simple Activity"

mainframe <b>activity</b> "Действия на лекции"

start
:Прийти на лекцию;
:Послушать первые 10 минут;
if (Лекция интересная?) then (Да)
    :Слушать дальше;
else (Нет)
    :Уснуть до конца лекции;
    :Проснуться;
endif
:Пойти домой;
stop
@enduml